---
abstract: 'A Gateway interface to send SMS text to celular phones using SMSTrend services'
author:
  - 'Hector Valverde <hvalverde@uma.es>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: smscli
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SSLeay: 0.64
  HTTP::Request::Common: 6.06
  IO::Socket::SSL: 1.77
  LWP::UserAgent: 6.04
  perl: 5.006
version: 2.16
